### ISSUE TITLE
Update the ELK stack versions

### ISSUE THREAD

**Issue by jean-lourenco** [docker-gallery/EnterpriseApplicationLog#1]
With the recent release of the [ELK stack version 5](https://www.elastic.co/blog/elastic-stack-5-0-0-released?storm=banner&elektra=home) the docker images on the script could be updated as well.

**Comment by luizcarlosfaria** [comment]
Thank you,  Jean,  I'll look new features and breaking changes to understand about how to be up-to-date.

**Comment by luizcarlosfaria** [comment]
[Release 2.0 - ELK Stack 5.0 - RabbitMQ 3.6](https://github.com/docker-gallery/EnterpriseApplicationLog/releases/tag/v2.0) was created in regards of your issue. 
Thank you!
