### ISSUE TITLE
Erro "No Living connections" ao acessar o Kibana

### ISSUE THREAD

**Issue by luisrjbr** [docker-gallery/EnterpriseApplicationLog#4]
Boa tarde!

Ao acessar o Kibana recebo as seguintes mensagens:

---------------Kibana------------------------------------

ID | Status
-- | --
ui settings | Elasticsearch plugin is red
plugin:kibana@5.6.4 | Ready
plugin:elasticsearch@5.6.4 | Unable to connect to Elasticsearch at http://elasticsearch:9200.
plugin:xpack_main@5.6.4 | Unable to connect to Elasticsearch at http://elasticsearch:9200.
plugin:graph@5.6.4 | Unable to connect to Elasticsearch at http://elasticsearch:9200.
plugin:monitoring@5.6.4 | Ready
plugin:reporting@5.6.4 | Unable to connect to Elasticsearch at http://elasticsearch:9200.
plugin:searchprofiler@5.6.4 | Unable to connect to Elasticsearch at http://elasticsearch:9200.
plugin:ml@5.6.4 | No Living connections
plugin:tilemap@5.6.4 | Unable to connect to Elasticsearch at http://elasticsearch:9200.
plugin:watcher@5.6.4 | Unable to connect to Elasticsearch at http://elasticsearch:9200.
plugin:grokdebugger@5.6.4 | Ready
plugin:upgrade@5.6.4 | Unable to connect to Elasticsearch at http://elasticsearch:9200.
plugin:console@5.6.4 | Ready
plugin:metrics@5.6.4 | Ready
plugin:timelion@5.6.4 | Ready

----------------Docker:---------------------------------------

luis.augusto@EPBRRJWKS013 C:\Users\luis.augusto
> docker images
REPOSITORY                                      TAG                   IMAGE ID            CREATED             SIZE
rabbitmq                                        3-management-alpine   21d4ff1bda19        4 weeks ago         85.5MB
docker.elastic.co/kibana/kibana                 5.6.4                 ec9ec2836846        3 months ago        675MB
docker.elastic.co/logstash/logstash             5.6.4                 9ab56ee8be2c        3 months ago        635MB
docker.elastic.co/elasticsearch/elasticsearch   5.6.4                 a9a9a2620d66        3 months ago        659MB

luis.augusto@EPBRRJWKS013 C:\Users\luis.augusto
> docker ps
CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS              PORTS
                                                    NAMES
45eb480a033a        docker.elastic.co/kibana/kibana:5.6.4       "/bin/sh -c /usr/loc…"   45 minutes ago      Up 45 minutes       0.0.0.0:5601->5601/tcp
                                                    Kibana
8b2a6b561337        docker.elastic.co/logstash/logstash:5.6.4   "/usr/local/bin/dock…"   45 minutes ago      Up 45 minutes       5044/tcp, 9600/tcp
                                                    LogStash
9f32ce79e552        rabbitmq:3-management-alpine                "docker-entrypoint.s…"   45 minutes ago      Up 45 minutes       4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp, 15671/tcp, 25672/tcp, 0.0.0.0:15672->15672/tcp   RabbitMQ

Saberia informar o que pode ser? Obrigado.

**Comment by luisrjbr** [comment]
Resolvido! Aumentei a memória do docker para 3GB e consegui inicializar o container do Elasticsearch.

**Comment by luizcarlosfaria** [comment]
Desculpe pela demora, obrigado pelo feedback e que bom que conseguiu resolver!
