### ISSUE TITLE
MetricBeat - Error on field 'count': Missing field: count, Error: Key disk_reads not found

### ISSUE THREAD

**Issue by perez-danilo** [docker-gallery/EnterpriseApplicationLog#5]
Boa tarde,

realizei o pul do projeto e estou tendo um problema com o metricbeat, depois de dar as permissões corretas no yml dele, consegui subir só que infeliziemnte estou recebendo a seguinte mensagem.

metricbeat       | 2018-03-28T21:10:49.040Z	ERROR	schema/schema.go:41	Error on field 'count': Missing field: count, Error: Key disk_reads not found

Seria configuração?

Muito obrigado

**Comment by luizcarlosfaria** [comment]
Eu vou verificar isso

**Comment by luizcarlosfaria** [comment]
Esse erro foi reportado no elastic.co ( https://discuss.elastic.co/t/metricbeat-rabbitmq-module-issues/125751 ).

Estou vendo algumas workarounds para resolver a questão.
