### ISSUE TITLE
Redirecionar logs do nginx

### ISSUE THREAD

**Issue by Fabioh** [docker-gallery/EnterpriseApplicationLog#8]
Seria possível redirecionar os logs do nginx para essa solução?

**Comment by luizcarlosfaria** [comment]
Eu implantei, com uma customização para isso.

Faz sentido customizar o log do NGINX para gerar um JSON (pra você ter flexibilidade com o formato) e em seguida o logstash importa pra mim. 

Eu já apresentei isso no gago.io, dockerdefinitivo.com ou no canal .net, sinceramente não lembro.
